env: '${ENV:prod}'

spring:
  profiles:
    active: '${env}'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    default-property-inclusion: non_null
  liquibase:
    changelog: 'classpath:changelog/db.changelog-master.yaml'
  mail:
    host: smtp.gmail.com
    port: '587'
    username: osinagalj@gmail.com
    password: oovjrafvkamvssfw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  validation:
    base-url: '${application.base-url}/auth/validate'
    forgot-password: '${application.base-url}/auth/validate-forgot-password'
  from-email: no-reply@ensolvers.com
  sign-up:
    enabled: '${SIGN_UP_ENABLED:true}'
ensolvers:
  security:
    enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
token:
  dev: '${TOKEN_DEV:abcd}'

info:
  application:
    name: spring-back-tesis
    description: Testing.
    author: Lautaro Osinaga
    version: '@0.1@'


PROD_DB_HOST: containers-us-west-195.railway.app
PROD_DB_PORT: 7107
PROD_DB_NAME: railway
PROD_DB_PASSWORD: yMXKKFdJhiNwHyD98gcO
PROD_DB_USERNAME: postgres
