application:
  base-url: 'http://lo-tesis-backend.herokuapp.com'
  front:
    base-url: '${APP_FRONT_BASE_URL:https://tesis-frontend-material-kit.vercel.app}'
  validation-base-url: '${application.front.base-url}/auth/validate'



spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-blog
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
