server:
  port: ${PORT:8080}
  address: 0.0.0.0
application:
  base-url: 'https://tesis-backend-production.up.railway.app'
  front:
    base-url: 'https://tesis-frontend-material-pg8yo2tr1-osinagalj-8375s-projects.vercel.app/'
  validation-base-url: '${application.front.base-url}/auth/validate'

PROD_DB_HOST: turntable.proxy.rlwy.net
PROD_DB_PORT: 22216
PROD_DB_NAME: railway
PROD_DB_PASSWORD: aDfSdGgsPXuGSHVUAHOfCRGmODjQATCm
PROD_DB_USERNAME: postgres

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://${PROD_DB_HOST:turntable.proxy.rlwy.net}:${PROD_DB_PORT:22216}/${PROD_DB_NAME:postgres}}
    username: ${PROD_DB_USERNAME:postgres}
    password: ${PROD_DB_PASSWORD:aDfSdGgsPXuGSHVUAHOfCRGmODjQATCm}
    name: spring-blog
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
