application:
  base-url: 'http://lo-tesis-backend.herokuapp.com'
  front:
    base-url: '${APP_FRONT_BASE_URL:https://tesis-frontend-material-kit.vercel.app}'
  validation-base-url: '${application.front.base-url}/auth/validate'

spring:
  datasource:
    url: 'jdbc:postgresql://dpg-ces55aen6mphf4o7e8lg-a.oregon-postgres.render.com:5432/tesis_database'
    username: tesis_database_user
    password: BjMReqGdCIeW7IDZ8N1rNozp7TFfbV4Y
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: '${HIKARI_MAXIMUM_POOL_SIZE:20}'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
