server:
  port: '8080'
application:
  base-url: '${APP_BASE_URL:http://localhost:8080}'
  front:
    base-url: '${APP_FRONT_BASE_URL:http://localhost:3000}'
  validation-base-url: '${application.front.base-url}/auth/validate'
#PostgresSQL

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:h2:mem:mydatabase
    username: sa
    password:
    driverClassName: org.h2.Driver

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect