server:
  port: '8080'
application:
  base-url: '${APP_BASE_URL:http://localhost:8080}'
  front:
    base-url: '${APP_FRONT_BASE_URL:http://localhost:3000}'
  validation-base-url: '${application.front.base-url}/auth/validate'
  validation:
    forgot-password: '${application.front.base-url}/reset-password'
#PostgresSQL

spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect